ping: "&7Ping &8» &c%player_ping%ms"
ping-target: "&7%player_name%'s Ping &8» &c%player_ping%ms"
player-first-join: "&c&lWELCOME &c%player_name%&7, for joining us for the first time!"
player-join: "&c%player_name% &7has joined the server."
player-quit: "&c%player_name% &7has left the server."